version: '3'

services:
  app:
    build: ./app
    ports:
      - "5000:5000"
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    networks:
      - app-network

  nginx:
    image: "nginx:alpine"
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

